### ISSUE TITLE
怎么监听到手势离开的事件

### ISSUE THREAD

**Issue by Thank4** [mcxinyu/ScheduleTimeRuler#4]
你好，感谢开源。能够把那个当前事件线和文字设置大小的方法暴露出来吗？

**Comment by mcxinyu** [comment]
游标线`cursorLine`就是时间线，字体大小有很多`xxxxTextSize`，如果还不满足可以继承，甚至 fork 仓库自行修改。

项目中的字段基本都是 public 的，最不济也可以动态修改后手动调用 `View#invalidate()` 刷新。

**Comment by mcxinyu** [comment]
关于手势有好几个 listener 方法，其中滚动监听有 `OnScrollListener` 接口，通过 `TimeRulerView#onScrollListener` 设置。

**Comment by Thank4** [comment]
> 游标线`cursorLine`就是时间线，字体大小有很多`xxxxTextSize`，如果还不满足可以继承，甚至 fork 仓库自行修改。
> 
> 项目中的字段基本都是 public 的，最不济也可以动态修改后手动调用 `View#invalidate()` 刷新。



> 游标线`cursorLine`就是时间线，字体大小有很多`xxxxTextSize`，如果还不满足可以继承，甚至 fork 仓库自行修改。
> 
> 项目中的字段基本都是 public 的，最不济也可以动态修改后手动调用 `View#invalidate()` 刷新。

好的，感谢回复！目前kotlin还没有学习，不过大体能看懂，后期有能力了fork修改，再次感谢开源
