### ISSUE TITLE
How is Today change?

### ISSUE THREAD

**Issue by tolgatasci** [mcxinyu/ScheduleTimeRuler#5]
I want show listing style today but other day like today.

I changed this veriable but didn't work
cursorTimeValue  = ?

**Comment by mcxinyu** [comment]
Sorry, this program only displays a view of one day, which has nothing to do with the current day.

Perhaps I didn't understand the meaning you were trying to convey correctly. 
Can you provide an example?

**Comment by tolgatasci** [comment]
I can list today. If a user selects a past date. I should show that day as the same day.

**Comment by mcxinyu** [comment]
I'm sorry.
At the beginning of my design, I did not consider the situation or requirement of multiple consecutive days together. If you still need this library, I suggest using the `ViewPager` to display it separately every day, or imitating this library to achieve your ideas.

**Comment by tolgatasci** [comment]
thank you
